#!/usr/bin/env bash
# scripts/lib/clerk-launchd-lib.sh
# comms-orch#18: pure, side-effect-free logic behind the per-seat clerk launchd deploy. Nothing in
# this file touches the registry, launchctl, or the real filesystem (beyond stdout) -- it can be
# sourced alone in a test with zero ambient state, mirroring agencyos-terminal-driver's
# relaunch-lib.sh split between pure decision logic and the live script that calls it.
set -u

# ── Naming (comms-orch#18 item 5 / #11 item 6: log + job paths discoverable programmatically,
# never hand-typed or hardcoded at each call site) ──────────────────────────────────────────────

# One launchd job per seat clerk (never one shared job across seats): each clerk carries its own
# seat identity (SEAT_NSEC, SEAT_ROLE) via distinct environment, and launchd's EnvironmentVariables
# dict is per-Label, not per-invocation -- a single parameterised job cannot hold N different
# identities at once. N seats therefore means N Labels, one plist each.
clerk_plist_label(){
  printf 'com.civilization.buzz-seat-clerk-%s' "$1"
}

clerk_plist_filename(){
  printf '%s.plist' "$(clerk_plist_label "$1")"
}

clerk_wrapper_filename(){
  printf 'run-clerk-%s.sh' "$1"
}

# launchd's own stdout/stderr redirect for the process, distinct from (and complementary to) the
# clerk's own internal durable log (comms-orch#11 slice B's clerk_log_path): the internal log
# captures structured app-level lines the binary itself writes; this captures anything printed
# outside that harness (a Rust panic before any handler runs, a dynamic-linker error, etc) that
# would otherwise vanish into launchd's own default log with no per-seat attribution.
clerk_launchd_stdout_path(){
  printf '%s/buzz-seat-clerk-%s.launchd-stdout.log' "$1" "$2"
}

clerk_launchd_stderr_path(){
  printf '%s/buzz-seat-clerk-%s.launchd-stderr.log' "$1" "$2"
}

# ── Wrapper script rendering ─────────────────────────────────────────────────────────────────
# Same secret-handling shape as agencyos-terminal-driver's relaunch.sh run-clerk-$a.sh: the
# wrapper's OWN file content never contains the nsec value, only the KEYVAR *variable name* --
# `export SEAT_NSEC="${$KEYVAR}"` is a literal, unexpanded bash reference until this script
# actually runs and sources ENVLOCAL, which is the only place the real secret ever exists. A
# generated plist or wrapper file on disk therefore never carries a live credential.
#   $1 clerk_bin   $2 envlocal_path   $3 keyvar_name   $4 relay_url   $5 seat_role
#   $6 seat_session $7 wake_file  $8 readack_file  $9 claim_dir  $10 clerk_log_dir
render_clerk_wrapper_script(){
  local clerk_bin="$1" envlocal="$2" keyvar="$3" relay_url="$4" seat_role="$5"
  local seat_session="$6" wake_file="$7" readack_file="$8" claim_dir="$9" clerk_log_dir="${10}"
  cat <<WRAP
#!/usr/bin/env bash
# GENERATED by scripts/generate-clerk-launchd.sh -- do not hand-edit, re-run the generator.
# comms-orch#18: launchd ProgramArguments target for one seat's clerk daemon.
set -euo pipefail
set -a
. "$envlocal"
set +a
export SEAT_NSEC="\${$keyvar}"
export RELAY_URL="$relay_url"
export SEAT_ROLE="$seat_role"
export SEAT_SESSION="$seat_session"
export WAKE_FILE="$wake_file"
export READACK_FILE="$readack_file"
export CLAIM_DIR="$claim_dir"
export CLERK_LOG_DIR="$clerk_log_dir"
exec "$clerk_bin"
WRAP
}

# ── Plist rendering ──────────────────────────────────────────────────────────────────────────
# Shells out to python3's plistlib rather than hand-building XML: plist string escaping (quotes,
# ampersands, control characters in a path) is exactly the class of bug a template string invites,
# and plistlib.dump is the same tool relaunch-lib.sh's js_string_literal reaches for for JS string
# escaping -- delegate correctness to a real serializer instead of re-deriving escaping rules.
#   $1 label  $2 wrapper_path  $3 stdout_path  $4 stderr_path
render_clerk_plist(){
  local label="$1" wrapper_path="$2" stdout_path="$3" stderr_path="$4"
  python3 - "$label" "$wrapper_path" "$stdout_path" "$stderr_path" <<'PY'
import plistlib, sys
label, wrapper_path, stdout_path, stderr_path = sys.argv[1:5]
doc = {
    "Label": label,
    "ProgramArguments": [wrapper_path],
    "RunAtLoad": True,
    "KeepAlive": True,
    "StandardOutPath": stdout_path,
    "StandardErrorPath": stderr_path,
}
sys.stdout.buffer.write(plistlib.dumps(doc, fmt=plistlib.FMT_XML))
PY
}
