#!/usr/bin/env bash
# scripts/lib/clerk-launchd-lib.sh
# comms-orch#18: pure, side-effect-free logic behind the per-seat clerk launchd deploy. Nothing in
# this file touches the registry, launchctl, or the real filesystem (beyond stdout) -- it can be
# sourced alone in a test with zero ambient state, mirroring agencyos-terminal-driver's
# relaunch-lib.sh split between pure decision logic and the live script that calls it.
set -u

# ── Naming (comms-orch#18 item 5 / #11 item 6: log + job paths discoverable programmatically,
# never hand-typed or hardcoded at each call site) ──────────────────────────────────────────────

# One launchd job per seat clerk (never one shared job across seats): each clerk carries its own
# seat identity (SEAT_NSEC, SEAT_ROLE) via distinct environment, and launchd's EnvironmentVariables
# dict is per-Label, not per-invocation -- a single parameterised job cannot hold N different
# identities at once. N seats therefore means N Labels, one plist each.
clerk_plist_label(){
  printf 'com.civilization.buzz-seat-clerk-%s' "$1"
}

clerk_plist_filename(){
  printf '%s.plist' "$(clerk_plist_label "$1")"
}

clerk_wrapper_filename(){
  printf 'run-clerk-%s.sh' "$1"
}

# Reverse of clerk_plist_filename (opeff#1210): recover a seat alias from a generated plist's
# filename, so the loader can enumerate DEPLOY_DIR directly instead of re-reading the registry.
clerk_alias_from_plist_filename(){
  local base="${1%.plist}"
  printf '%s' "${base#com.civilization.buzz-seat-clerk-}"
}

# opeff#1210: path to the bare background clerk's literal pid file, written by
# agencyos-comms-orchestrator's infra/clerks/tab-clerk-<alias>.sh (`echo $$ > .../run/clerk-<alias>.pid`).
# Named here, once, so the loader and any future caller derive the same path instead of each
# re-typing the "clerk-%s.pid" pattern.
clerk_run_pid_path(){
  printf '%s/clerk-%s.pid' "$1" "$2"
}

# launchd's own stdout/stderr redirect for the process, distinct from (and complementary to) the
# clerk's own internal durable log (comms-orch#11 slice B's clerk_log_path): the internal log
# captures structured app-level lines the binary itself writes; this captures anything printed
# outside that harness (a Rust panic before any handler runs, a dynamic-linker error, etc) that
# would otherwise vanish into launchd's own default log with no per-seat attribution.
clerk_launchd_stdout_path(){
  printf '%s/buzz-seat-clerk-%s.launchd-stdout.log' "$1" "$2"
}

clerk_launchd_stderr_path(){
  printf '%s/buzz-seat-clerk-%s.launchd-stderr.log' "$1" "$2"
}

# ── Wrapper script rendering ─────────────────────────────────────────────────────────────────
# Same secret-handling shape as agencyos-terminal-driver's relaunch.sh run-clerk-$a.sh: the
# wrapper's OWN file content never contains the nsec value, only the KEYVAR *variable name* --
# `export SEAT_NSEC="${$KEYVAR}"` is a literal, unexpanded bash reference until this script
# actually runs and sources its per-seat header file, which is the only place the real secret
# ever exists. A generated plist or wrapper file on disk therefore never carries a live credential.
#
# opeff#1227: the wrapper used to source agency-os/.env.local directly, which sits under
# Documents. launchd is refused under Documents on this host (Operation not permitted), so every
# launchd-started clerk crash-looped. The wrapper now sources $HOME/.local/agencyos/keys/<alias>.env
# instead -- written by scripts/place-clerk-keys.sh, never under Documents, never under a repo --
# and refuses loud, naming that script, if the header file is missing or not mode 0600.
#   $1 clerk_bin   $2 alias   $3 keyvar_name   $4 relay_url   $5 seat_role
#   $6 seat_session $7 wake_file  $8 readack_file  $9 claim_dir  $10 clerk_log_dir
#   $11 keys_dir (optional, defaults to $HOME/.local/agencyos/keys -- overridable so a test can
#   render a wrapper that points at a scratch header dir)
render_clerk_wrapper_script(){
  local clerk_bin="$1" alias="$2" keyvar="$3" relay_url="$4" seat_role="$5"
  local seat_session="$6" wake_file="$7" readack_file="$8" claim_dir="$9" clerk_log_dir="${10}"
  local keys_dir="${11:-\$HOME/.local/agencyos/keys}"
  local run_dir="${12:-\$HOME/.local/agencyos/run}"
  cat <<WRAP
#!/usr/bin/env bash
# GENERATED by scripts/generate-clerk-launchd.sh -- do not hand-edit, re-run the generator.
# comms-orch#18: launchd ProgramArguments target for one seat's clerk daemon.
set -euo pipefail
KEY_FILE="$keys_dir/$alias.env"
if [ ! -f "\$KEY_FILE" ]; then
  echo "run-clerk-$alias.sh: missing key file \$KEY_FILE -- run scripts/place-clerk-keys.sh --live first" >&2
  exit 1
fi
KEY_FILE_MODE=\$(stat -f '%Lp' "\$KEY_FILE" 2>/dev/null || stat -c '%a' "\$KEY_FILE" 2>/dev/null)
if [ "\$KEY_FILE_MODE" != "600" ]; then
  echo "run-clerk-$alias.sh: \$KEY_FILE must be mode 600 (got \$KEY_FILE_MODE) -- run scripts/place-clerk-keys.sh --live to regenerate it" >&2
  exit 1
fi
set -a
. "\$KEY_FILE"
set +a
export SEAT_NSEC="\${$keyvar}"
export RELAY_URL="$relay_url"
export SEAT_ROLE="$seat_role"
export SEAT_SESSION="$seat_session"
export WAKE_FILE="$wake_file"
export READACK_FILE="$readack_file"
export CLAIM_DIR="$claim_dir"
export CLERK_LOG_DIR="$clerk_log_dir"
# opeff#1210: the pid file is the source CLERKALIVE01, CLERKBIN01 and CLERKSTRAY01 read.
# Written here, before exec, so the pid is the clerk's own once exec replaces this shell.
# Under the home dir, outside every repo, where a launchd child is allowed to write.
# A restart overwrites it; a deliberate stop through load-clerk-launchd.sh removes it.
PID_DIR="$run_dir"
mkdir -p "\$PID_DIR"
echo "\$\$" > "\$PID_DIR/clerk-$alias.pid"
exec "$clerk_bin"
WRAP
}

# ── Plist rendering ──────────────────────────────────────────────────────────────────────────
# Shells out to python3's plistlib rather than hand-building XML: plist string escaping (quotes,
# ampersands, control characters in a path) is exactly the class of bug a template string invites,
# and plistlib.dump is the same tool relaunch-lib.sh's js_string_literal reaches for for JS string
# escaping -- delegate correctness to a real serializer instead of re-deriving escaping rules.
#   $1 label  $2 wrapper_path  $3 stdout_path  $4 stderr_path
render_clerk_plist(){
  local label="$1" wrapper_path="$2" stdout_path="$3" stderr_path="$4"
  python3 - "$label" "$wrapper_path" "$stdout_path" "$stderr_path" <<'PY'
import plistlib, sys
label, wrapper_path, stdout_path, stderr_path = sys.argv[1:5]
doc = {
    "Label": label,
    "ProgramArguments": [wrapper_path],
    "RunAtLoad": True,
    "KeepAlive": True,
    "StandardOutPath": stdout_path,
    "StandardErrorPath": stderr_path,
}
sys.stdout.buffer.write(plistlib.dumps(doc, fmt=plistlib.FMT_XML))
PY
}
